# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: create_placeholder_response_model.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class CreatePlaceholderResponseModel(betterproto.Message):
    media_ids: List[str] = betterproto.string_field(1)
