# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: create_placeholder_request.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class CreatePlaceholderRequest(betterproto.Message):
    num_pending_media: int = betterproto.int32_field(1)
