# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: tinder/services/mediaservice/create_placeholder_response_model.proto, tinder/services/mediaservice/delete_media_response_model.proto, tinder/services/mediaservice/error.proto, tinder/services/mediaservice/meta.proto, tinder/services/mediaservice/order_media_response_model.proto, tinder/services/mediaservice/update_photo_avatar_response_model.proto, tinder/services/mediaservice/upload_facebook_photo_response_model.proto, media_response_wrapper.proto
# plugin: python-betterproto
from dataclasses import dataclass
from datetime import datetime
from typing import List
from .media import *

import betterproto


@dataclass
class CreatePlaceholderResponseModel(betterproto.Message):
    media_ids: List[str] = betterproto.string_field(1)


@dataclass
class DeleteMediaResponseModel(betterproto.Message):
    succeeded: List[str] = betterproto.string_field(1)
    not_found: List[str] = betterproto.string_field(2)
    failed: List[str] = betterproto.string_field(3)


@dataclass
class ErrorProto(betterproto.Message):
    code: int = betterproto.int32_field(1)
    message: str = betterproto.string_field(2)


@dataclass
class MetaProto(betterproto.Message):
    upstream_time: datetime = betterproto.message_field(1)
    start_time: datetime = betterproto.message_field(2)


@dataclass
class OrderMediaResponseModel(betterproto.Message):
    succeeded: bool = betterproto.bool_field(1)


@dataclass
class UpdatePhotoAvatarResponseModel(betterproto.Message):
    succeeded: bool = betterproto.bool_field(1)


@dataclass
class UploadFacebookPhotoResponseModel(betterproto.Message):
    succeeded: bool = betterproto.bool_field(1)


@dataclass
class ClientDataProto(betterproto.Message):
    meta: "MetaProto" = betterproto.message_field(1)
    error: "ErrorProto" = betterproto.message_field(2)
    create_placeholder_response_model: "CreatePlaceholderResponseModel" = (
        betterproto.message_field(16, group="payload")
    )
    delete_media_response_model: "DeleteMediaResponseModel" = betterproto.message_field(
        17, group="payload"
    )
    media_response_model: "Media" = betterproto.message_field(18, group="payload")
    order_media_response_model: "OrderMediaResponseModel" = betterproto.message_field(
        19, group="payload"
    )
    update_photo_avatar_response_model: "UpdatePhotoAvatarResponseModel" = (
        betterproto.message_field(20, group="payload")
    )
    upload_facebook_photo_response_model: "UploadFacebookPhotoResponseModel" = (
        betterproto.message_field(21, group="payload")
    )
