# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: order_media_request.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class OrderMediaRequest(betterproto.Message):
    media_ids: List[str] = betterproto.string_field(1)
